---
# Woodpecker CI Pipeline for Meshtastic MQTT Bot
# https://woodpecker-ci.org/docs/usage/intro

when:
  - event: [push, pull_request, tag, manual]
    branch: [master, main, develop]

# Use local backend without Docker plugin-git clone
clone:
  git:
    image: /bin/sh
    disable: true

steps:
  # Manual clone using Forgejo HTTP (avoids plugin-git)
  - name: clone
    image: /bin/sh
    commands:
      - set -ex
      # If this directory is already a git repo, just fetch + reset to the desired commit
      - |
        if [ -d ".git" ]; then
          git fetch origin
          if [ -n "${CI_COMMIT_SHA}" ]; then
            git checkout "${CI_COMMIT_SHA}"
          else
            git checkout master
            git reset --hard origin/master
          fi
        else
          # Use the CI-provided clone URL (with credentials) if available; otherwise fall back to plain HTTP
          [ -n "${CI_REPO_CLONE_URL}" ] && git clone "${CI_REPO_CLONE_URL}" . || git clone http://192.168.8.191:3000/mac/baymesh-mqtt-bot.git .
          if [ -n "${CI_COMMIT_SHA}" ]; then
            git checkout "${CI_COMMIT_SHA}"
          else
            git checkout master
          fi
        fi
    when:
      event: [push, pull_request, tag, manual]

  # Lint & formatting checks (Black + Flake8)
  - name: lint
    image: /bin/sh
    commands:
      - set -ex
      - rm -rf .venv || true
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - black --check src tests --line-length 79
      - flake8 src tests
    when:
      event: [push, pull_request, manual]

  # Run tests
  - name: test
    image: /bin/sh
    commands:
      - set -ex
      # Use a fresh virtualenv per workspace so each pipeline has a clean Python env
      - rm -rf .venv || true
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pytest --cov=src --cov-report=term-missing
    when:
      event: [push, pull_request, manual]

  # Build frontend (dashboard)
  - name: build-frontend
    image: /bin/sh
    commands:
      - cd dashboard
      - npm ci
      - npm run build
      - ls -lah dist/
    when:
      event: [push, tag, manual]
      branch: [master, main]

  # Deploy to baymesh-mqtt-bot host via SSH (bare-metal, no Docker)
  - name: deploy-to-pi
    image: /bin/sh
    commands:
      - set -ex
      # Deploy latest code to the baymesh-mqtt-bot host, rebuild dashboard, and restart systemd service
      - |
        ssh -i /root/.ssh/woodpecker-deploy -o StrictHostKeyChecking=no root@192.168.8.114 << 'EOF'
        set -ex
        cd /opt/baymesh-mqtt-bot
        git pull --ff-only
        # Ensure Node.js tooling is available for dashboard build
        command -v npm >/dev/null 2>&1 || (apt-get update && apt-get install -y nodejs npm)
        cd dashboard
        npm ci
        npm run build
        cd ..
        systemctl restart meshtastic-stats-bot.service
        EOF
    when:
      event: [push]
      branch: [master, main]
      # Only deploy when tests pass
      status: [success]
