---
# Woodpecker CI Pipeline for Meshtastic MQTT Bot
# https://woodpecker-ci.org/docs/usage/intro

when:
  - event: [push, pull_request, tag, manual]
    branch: [master, main, develop]

# Use local backend without Docker plugin-git clone
clone:
  git:
    image: /bin/sh
    disable: true

steps:
  # Manual clone using Forgejo HTTP (avoids plugin-git)
  - name: clone
    image: /bin/sh
    commands:
      - set -ex
      # If this directory is already a git repo, just fetch + reset to the desired commit
      - |
        if [ -d ".git" ]; then
          git fetch origin
          if [ -n "${CI_COMMIT_SHA}" ]; then
            git checkout "${CI_COMMIT_SHA}"
          else
            git checkout master
            git reset --hard origin/master
          fi
        else
          # Use the CI-provided clone URL (with credentials) if available; otherwise fall back to plain HTTP
          [ -n "${CI_REPO_CLONE_URL}" ] && git clone "${CI_REPO_CLONE_URL}" . || git clone http://192.168.8.191:3000/mac/baymesh-mqtt-bot.git .
          if [ -n "${CI_COMMIT_SHA}" ]; then
            git checkout "${CI_COMMIT_SHA}"
          else
            git checkout master
          fi
        fi
    when:
      event: [push, pull_request, tag, manual]

  # Lint & formatting checks (Black + Flake8)
  - name: lint
    image: /bin/sh
    commands:
      - set -ex
      - rm -rf .venv || true
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - black --check src tests --line-length 79
      - flake8 src tests
    when:
      event: [push, pull_request, manual]

  # Run tests
  - name: test
    image: /bin/sh
    commands:
      - set -ex
      # Use a fresh virtualenv per workspace so each pipeline has a clean Python env
      - rm -rf .venv || true
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pytest --cov=src --cov-report=term-missing
    when:
      event: [push, pull_request, manual]

  # Build frontend (dashboard)
  - name: build-frontend
    image: /bin/sh
    commands:
      - cd dashboard
      - npm ci
      - npm run build
      - ls -lah dist/
    when:
      event: [push, tag, manual]
      branch: [master, main]

  # Deploy to baymesh-mqtt-bot host via SSH (bare-metal, no Docker)
  - name: deploy-to-pi
    image: /bin/sh
    commands:
      - set -ex
      # Deploy latest code to the baymesh-mqtt-bot host, rebuild dashboard, and restart systemd service
      - |
        ssh -i /root/.ssh/woodpecker-deploy -o StrictHostKeyChecking=no root@192.168.8.114 << 'EOF'
        set -ex
        cd /opt/baymesh-mqtt-bot
        git pull --ff-only
        # Ensure Python deps are current for migrations
        python3 -m venv .venv
        . .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        # Run database migrations
        alembic upgrade head
        # Ensure Node.js tooling is available for dashboard build
        command -v npm >/dev/null 2>&1 || (apt-get update && apt-get install -y nodejs npm)
        cd dashboard
        npm ci
        npm run build
        cd ..
        # Ensure Docker for promtail (remote Loki)
        command -v docker >/dev/null 2>&1 || (apt-get update && apt-get install -y docker.io)
        systemctl enable --now docker || true
        # Restart promtail to ship logs to remote Loki
        docker rm -f meshtastic-promtail || true
        PROMTAIL_HOSTNAME=$(hostname) docker run -d \
          --name meshtastic-promtail \
          --restart unless-stopped \
          -e PROMTAIL_HOSTNAME \
          -v /var/log/journal:/var/log/journal:ro \
          -v /run/log/journal:/run/log/journal:ro \
          -v /etc/machine-id:/etc/machine-id:ro \
          -v /var/lib/promtail:/var/lib/promtail \
          -v /opt/baymesh-mqtt-bot/observability/promtail-config.yml:/etc/promtail/config.yml:ro \
          grafana/promtail:2.9.4 -config.file=/etc/promtail/config.yml
        # Telegraf to forward Prometheus metrics to remote Influx
        docker rm -f meshtastic-telegraf || true
        if [ -n "${INFLUX_TOKEN}" ]; then
          HOSTNAME=$(hostname) INFLUX_TOKEN="${INFLUX_TOKEN}" docker run -d \
            --name meshtastic-telegraf \
            --restart unless-stopped \
            --network host \
            -e INFLUX_TOKEN \
            -e HOSTNAME \
            -v /opt/baymesh-mqtt-bot/observability/telegraf.conf:/etc/telegraf/telegraf.conf:ro \
            telegraf:1.30-alpine
        else
          echo "INFLUX_TOKEN not set; skipping telegraf deploy" >&2
        fi
        systemctl restart meshtastic-stats-bot.service
        EOF
    environment:
      INFLUX_TOKEN:
        from_secret: INFLUX_TOKEN
    when:
      event: [push]
      branch: [master, main]
      # Only deploy when tests pass
      status: [success]
