---
# Woodpecker CI Pipeline for Meshtastic MQTT Bot
# https://woodpecker-ci.org/docs/usage/intro

when:
  - event: [push, pull_request, tag, manual]
    branch: [master, main, develop]

# Use local backend without Docker plugin-git clone
clone:
  git:
    image: /bin/sh
    disable: true

steps:
  # Manual clone using Forgejo HTTP (avoids plugin-git)
  - name: clone
    image: /bin/sh
    commands:
      - set -ex
      # Determine repo URL (prefer CI-provided URL with credentials)
      - 'REPO_URL="${CI_REPO_CLONE_URL:-http://192.168.8.191:3000/mac/baymesh-mqtt-bot.git}"'
      # If this directory is already a git repo, just fetch + reset to the desired commit
      - |
        if [ -d ".git" ]; then
          git remote set-url origin "${REPO_URL}"
          git fetch origin
          if [ -n "${CI_COMMIT_SHA}" ]; then
            git checkout "${CI_COMMIT_SHA}"
          else
            git checkout master
            git reset --hard origin/master
          fi
        else
          git clone "${REPO_URL}" .
          if [ -n "${CI_COMMIT_SHA}" ]; then
            git checkout "${CI_COMMIT_SHA}"
          else
            git checkout master
          fi
        fi
    when:
      event: [push, pull_request, tag]

  # Run tests
  - name: test
    image: /bin/sh
    commands:
      - set -ex
      - pip3 install --upgrade pip
      - pip3 install -r requirements.txt
      - pytest --cov=src --cov-report=term-missing
    when:
      event: [push, pull_request]

  # Build frontend (dashboard)
  - name: build-frontend
    image: /bin/sh
    commands:
      - cd dashboard
      - npm ci
      - npm run build
      - ls -lah dist/
    when:
      event: [push, tag]
      branch: [master, main]

  # Deploy to Raspberry Pi via SSH
  - name: deploy-to-pi
    image: /bin/sh
    commands:
      - echo "Deploy step is not yet configured for local backend; skipping."
    when:
      event: [push]
      branch: [master, main]
      # Only deploy when tests pass
      status: [success]
