---
# Woodpecker CI Pipeline for Meshtastic MQTT Bot
# https://woodpecker-ci.org/docs/usage/intro

when:
  - event: [push, pull_request, tag]
    branch: [master, main, develop]

# Use local backend without Docker plugin-git clone
clone:
  git:
    image: alpine:3.19
    disable: true

steps:
  # Manual clone using Forgejo HTTP (avoids plugin-git)
  - name: clone
    image: alpine:3.19
    commands:
      - set -ex
      # Clean any existing checkout in the working directory
      - rm -rf .git ./* || true
      # Use the CI-provided clone URL so auth tokens / credentials are included
      - '[ -n "${CI_REPO_CLONE_URL}" ] && git clone "${CI_REPO_CLONE_URL}" . || git clone http://192.168.8.191:3000/mac/baymesh-mqtt-bot.git .'
      - '[ -n "${CI_COMMIT_SHA}" ] && git checkout "${CI_COMMIT_SHA}" || git checkout master'
    when:
      event: [push, pull_request, tag]

  # Run tests
  - name: test
    image: alpine:3.19
    commands:
      - set -ex
      - pip3 install --upgrade pip
      - pip3 install -r requirements.txt
      - pytest --cov=src --cov-report=term-missing
    when:
      event: [push, pull_request]

  # Build frontend (dashboard)
  - name: build-frontend
    image: alpine:3.19
    commands:
      - cd dashboard
      - npm ci
      - npm run build
      - ls -lah dist/
    when:
      event: [push, tag]
      branch: [master, main]

  # Deploy to Raspberry Pi via SSH
  - name: deploy-to-pi
    image: alpine:3.19
    commands:
      - echo "Deploy step is not yet configured for local backend; skipping."
    when:
      event: [push]
      branch: [master, main]
      # Only deploy when tests pass
      status: [success]

  # Notification on failure
  - name: notify-failure
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: deployments
      username: woodpecker
      template: >
        Build {{build.number}} failed for {{repo.name}}
        Branch: {{build.branch}}
        Commit: {{build.commit}}
        Author: {{build.author}}
    when:
      status: [failure]

