---
# Woodpecker CI Pipeline for Meshtastic MQTT Bot
# https://woodpecker-ci.org/docs/usage/intro

when:
  - event: [push, pull_request, tag, manual]
    branch: [master, main, develop]

# Use local backend without Docker plugin-git clone
clone:
  git:
    image: /bin/sh
    disable: true

steps:
  # Manual clone using Forgejo HTTP (avoids plugin-git)
  - name: clone
    image: /bin/sh
    commands:
      - set -ex
      # If this directory is already a git repo, just fetch + reset to the desired commit
      - |
        if [ -d ".git" ]; then
          git fetch origin
          if [ -n "${CI_COMMIT_SHA}" ]; then
            git checkout "${CI_COMMIT_SHA}"
          else
            git checkout master
            git reset --hard origin/master
          fi
        else
          # Use the CI-provided clone URL (with credentials) if available; otherwise fall back to plain HTTP
          [ -n "${CI_REPO_CLONE_URL}" ] && git clone "${CI_REPO_CLONE_URL}" . || git clone http://192.168.8.191:3000/mac/baymesh-mqtt-bot.git .
          if [ -n "${CI_COMMIT_SHA}" ]; then
            git checkout "${CI_COMMIT_SHA}"
          else
            git checkout master
          fi
        fi
    when:
      event: [push, pull_request, tag]

  # Run tests
  - name: test
    image: /bin/sh
    commands:
      - set -ex
      # Install Python deps into the system-managed environment (CI host) even though it's PEP 668 managed
      - python3 -m pip install --break-system-packages --upgrade pip
      - python3 -m pip install --break-system-packages -r requirements.txt
      - pytest --cov=src --cov-report=term-missing
    when:
      event: [push, pull_request]

  # Build frontend (dashboard)
  - name: build-frontend
    image: /bin/sh
    commands:
      - cd dashboard
      - npm ci
      - npm run build
      - ls -lah dist/
    when:
      event: [push, tag]
      branch: [master, main]

  # Deploy to Raspberry Pi via SSH
  - name: deploy-to-pi
    image: /bin/sh
    commands:
      - echo "Deploy step is not yet configured for local backend; skipping."
    when:
      event: [push]
      branch: [master, main]
      # Only deploy when tests pass
      status: [success]
