"""add_command_logs_table

Revision ID: 17be1cb500c7
Revises: 2b97c9f5a4dd
Create Date: 2025-11-30 19:44:16.263368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17be1cb500c7'
down_revision: Union[str, None] = '2b97c9f5a4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('mesh_id', sa.String(length=20), nullable=True),
    sa.Column('command', sa.String(length=255), nullable=False),
    sa.Column('response_sent', sa.Boolean(), nullable=False),
    sa.Column('rate_limited', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_command_logs_command', 'command_logs', ['command'], unique=False)
    op.create_index('ix_command_logs_timestamp', 'command_logs', ['timestamp'], unique=False)
    op.create_index('ix_command_logs_user_id', 'command_logs', ['user_id'], unique=False)
    op.drop_index('ix_message_gateways_message_id', table_name='message_gateways')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_message_gateways_message_id', 'message_gateways', ['message_id'], unique=False)
    op.drop_index('ix_command_logs_user_id', table_name='command_logs')
    op.drop_index('ix_command_logs_timestamp', table_name='command_logs')
    op.drop_index('ix_command_logs_command', table_name='command_logs')
    op.drop_table('command_logs')
    # ### end Alembic commands ###
