---
# Deployment pipeline - runs on push to master/main

when:
  event: [push]
  branch: [master, main]

steps:
  - name: build-frontend
    image: node:18-alpine
    commands:
      - cd dashboard
      - npm ci
      - npm run build
      - echo "Frontend build complete"

  - name: deploy-to-raspberry-pi
    image: appleboy/drone-ssh:1.7.2
    settings:
      host:
        from_secret: pi_host
      username:
        from_secret: pi_user  
      key:
        from_secret: pi_ssh_key
      port: 22
      command_timeout: 5m
      script:
        - |
          set -e
          echo "Deploying to Raspberry Pi..."
          cd /opt/meshtastic-mqtt-bot || cd ~/meshtastic-mqtt-bot
          
          echo "Pulling latest code..."
          git fetch --all
          git reset --hard origin/master
          
          echo "Stopping existing containers..."
          docker compose down || true
          
          echo "Rebuilding containers..."
          docker compose build --no-cache
          
          echo "Starting containers..."
          docker compose up -d
          
          echo "Waiting for services to start..."
          sleep 5
          
          echo "Checking service health..."
          docker compose ps
          docker compose logs --tail=20
          
          echo "Deployment complete!"
    when:
      status: [success]

  - name: verify-deployment
    image: curlimages/curl:8.5.0
    commands:
      - sleep 10
      - curl -f http://${PI_HOST}:8000/health || exit 1
      - echo "Health check passed!"
    environment:
      PI_HOST:
        from_secret: pi_host
    when:
      status: [success]

  - name: rollback-on-failure
    image: appleboy/drone-ssh:1.7.2
    settings:
      host:
        from_secret: pi_host
      username:
        from_secret: pi_user
      key:
        from_secret: pi_ssh_key
      port: 22
      script:
        - |
          echo "Deployment failed, rolling back..."
          cd /opt/meshtastic-mqtt-bot || cd ~/meshtastic-mqtt-bot
          git checkout HEAD~1
          docker compose down
          docker compose up -d
          echo "Rollback complete"
    when:
      status: [failure]

